databases:
  - name: herbcare-db
    databaseName: herbcare
    user: herbcare_user

services:
  - type: web
    name: herbcare-app
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan migrate --force && php artisan db:seed --force && php artisan config:clear && php artisan view:clear"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:bcB9icqce16ZATl0OVkxSwIAldJcbfWGnk1qjHFtjUQ=
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: herbcare-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: herbcare-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: herbcare-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: herbcare-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: herbcare-db
          property: password
